// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2026 Qwuille

#pragma once

#define VIAL_KEYBOARD_UID {0x2A, 0x97, 0x0F, 0x56, 0xAF, 0x69, 0x09, 0x6C}
#define VIAL_UNLOCK_COMBO_ROWS {0, 1}
#define VIAL_UNLOCK_COMBO_COLS {1, 1}

#define DYNAMIC_KEYMAP_MACRO_COUNT 64
#define VIAL_COMBO_ENTRIES 80
#define VIAL_TAP_DANCE_ENTRIES 8
#define TAP_CODE_DELAY 10

#define RGB_MATRIX_LED_COUNT 2
#define RGB_MATRIX_SPLIT {1, 1}
#define WS2812_PWM_DRIVER PWMD1
#define WS2812_PWM_CHANNEL 2
#define WS2812_PWM_PAL_MODE 1
#define WS2812_PWM_DMA_STREAM STM32_DMA1_STREAM5
#define WS2812_PWM_DMA_CHANNEL 5
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 180
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 170
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 96
#define RGB_MATRIX_SLEEP

#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE

#define SPLIT_TRANSACTION_IDS_USER CORNE_RGB_SYNC, CORNE_OWNER_SYNC

#define CORNE_CONTROL_BOARD_ID CORNE_BOARD_XTIPS_V4S_103C
#define CORNE_CONTROL_LED_COUNT 2
#define CORNE_CONTROL_LEFT_LED_COUNT 1
#define CORNE_CONTROL_DYNAMIC_LAYERS 9
#define CORNE_CONTROL_MAX_BRIGHTNESS RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define CORNE_CONTROL_EFFECT_COUNT 5
